spring:
        data:
              mongodb:
                      host: 127.0.0.1
                      database: safebox
                      port: 17011
        security:
                    enabled: false

security:
          token:
                secret:
                        key: developer
          ignored: /**
          basic:
                enabled: false
management:
            security:
                      enabled: false