spring:
        data:
              mongodb:
                      host: {MONGO_HOST}
                      database: {MONGO_DATABASE}
                      username: {MONGO_USERNAME}
                      password: {MONGO_PASSWORD}
                      port: {MONGO_PORT}
        security:
                    enabled: false

security:
          token:
                secret:
                        key: {TOKEN_KEY}
          ignored: /**
          basic:
                enabled: false
management:
            security:
                      enabled: false